### ISSUE TITLE
Update Transaction#is_coin_base()

### ISSUE THREAD

**Issue by Yamaguchi** [chaintope/rust-tapyrus#16]
The Trasaction#is_coin_base() return true if and only if only input in the transaction has no previous output(out point is null).

But in Tapyrus, coinbase transaction has a non-null out point.

https://github.com/chaintope/tapyrus-core/blob/master/doc/tapyrus/fix_transaction_malleability.md#tapyrus-transaction-structure

**Comment by rantan** [comment]
How about the below policy for this issue.

* Change the concept of null of OutPoint to that only txid is the default value. And it omits vout value.

According to the policy, the changes for the implementation should be below.

* change `OutPoint::is_null()` like below
```rust
pub fn is_null(&self) -> bool {
    *self.txid == Default::default()
}
```
* Re-create the documentation test, which was removed in PR #14.
* Remove `OutPoint::null()` function.
* Leave something documents about a outpoint in a input of a coinbase tx as comments.

**Comment by Yamaguchi** [comment]
>Change the concept of null of OutPoint to that only txid is the default value. And it omits vout value.

if you have two outpoints which are "null":
```
point_a = OutPoint { txid: Default::default(), vout: 1}
```
and 
```
point_b = OutPoint { txid: Default::default(), vout: 2}
```

in this case, point_a is "null" and point_b is "null", but point_a != point_b.
I think this situation may generate another bug or confusion.

**Comment by Yamaguchi** [comment]
On the other hand, OutPoint::null() method is used as a default value of OutPoint.
I think we should leave this method as is.

**Comment by rantan** [comment]
umm, I see. You are right.
